apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: ecommerce
type: Opaque
stringData:
  ORDER_DATABASE_URL: postgresql://orderservice:your-password@order-postgres:5432/orderdb