apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: ecommerce
type: Opaque
stringData:
  PRODUCT_DATABASE_URL: postgresql://productservice:your-password@product-postgres:5432/productdb