apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-service-config
  namespace: ecommerce
data:
  USER_SERVICE_URL: "http://user-service:8000"
  PRODUCT_SERVICE_URL: "http://product-service:8001"
  ORDER_SERVICE_URL: "http://order-service:8002"
  CART_SERVICE_URL: "http://cart-service:8003"