apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: ecommerce
type: Opaque
stringData:
  JWT_SECRET_KEY: your-jwt-secret
  USER_DATABASE_URL: postgresql://userservice:your-password@user-postgres:5432/userdb